# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bantik_blog}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bantik"]
  s.date = %q{2011-04-22}
  s.description = %q{An engine for search-engine-optimized blog management.}
  s.email = %q{corey@seologic.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.homepage = %q{https://mir.unfuddle.com/a#/projects/31942}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{An engine for search-engine-optimized blog management.}
  s.test_files = [
    "spec/blueprints.rb",
    "spec/models/blog_spec.rb",
    "spec/models/comment_spec.rb",
    "spec/models/post_spec.rb",
    "spec/models/topic_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<carrierwave>, [">= 0"])
      s.add_runtime_dependency(%q<ckeditor>, [">= 0"])
      s.add_runtime_dependency(%q<gravatar_image_tag>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta.17"])
      s.add_runtime_dependency(%q<mongoid_taggable>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<recaptcha>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, ["= 2.12.2"])
      s.add_runtime_dependency(%q<scaffold_logic>, [">= 1.0.3"])
      s.add_runtime_dependency(%q<SystemTimer>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<carrierwave>, [">= 0"])
      s.add_dependency(%q<ckeditor>, [">= 0"])
      s.add_dependency(%q<gravatar_image_tag>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.17"])
      s.add_dependency(%q<mongoid_taggable>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.1"])
      s.add_dependency(%q<recaptcha>, [">= 0"])
      s.add_dependency(%q<rmagick>, ["= 2.12.2"])
      s.add_dependency(%q<scaffold_logic>, [">= 1.0.3"])
      s.add_dependency(%q<SystemTimer>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<carrierwave>, [">= 0"])
    s.add_dependency(%q<ckeditor>, [">= 0"])
    s.add_dependency(%q<gravatar_image_tag>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.17"])
    s.add_dependency(%q<mongoid_taggable>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.1"])
    s.add_dependency(%q<recaptcha>, [">= 0"])
    s.add_dependency(%q<rmagick>, ["= 2.12.2"])
    s.add_dependency(%q<scaffold_logic>, [">= 1.0.3"])
    s.add_dependency(%q<SystemTimer>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

